# Generated by Django 6.0.2 on 2026-03-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensegroup',
            name='participant_count',
            field=models.IntegerField(default=1),
        ),
    ]
