# Generated by Django 6.0.2 on 2026-03-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_budget_group_remove_groupmember_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRAVEL', 'Travel'), ('UTILITIES', 'Utilities'), ('EDUCATION', 'Education'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
