# Generated by Django 6.0.2 on 2026-03-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def assign_budget_owners(apps, schema_editor):
    Budget = apps.get_model('core', 'Budget')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])

    owner = User.objects.filter(is_superuser=True).order_by('id').first()
    if owner is None:
        owner = User.objects.order_by('id').first()
    if owner is None:
        return

    Budget.objects.filter(user__isnull=True).update(user=owner)


def normalize_expense_descriptions(apps, schema_editor):
    Expense = apps.get_model('core', 'Expense')
    Expense.objects.filter(description__isnull=True).update(description='')


def create_sample_category_tree(apps, schema_editor):
    Category = apps.get_model('core', 'Category')
    table_name = Category._meta.db_table
    existing_columns = {
        column.name
        for column in schema_editor.connection.introspection.get_table_description(
            schema_editor.connection.cursor(),
            table_name,
        )
    }

    # This migration only changed state for `parent`, so skip the sample tree
    # when the backing column does not exist in the actual database.
    if 'parent_id' not in existing_columns:
        return

    education, _ = Category.objects.get_or_create(
        name='Education',
        parent=None,
        defaults={'category_type': 'Education'},
    )
    fees, _ = Category.objects.get_or_create(
        name='Fees',
        parent=education,
        defaults={'category_type': 'Education'},
    )
    school_fees, _ = Category.objects.get_or_create(
        name='School Fees',
        parent=fees,
        defaults={'category_type': 'Education'},
    )
    Category.objects.get_or_create(
        name='College Fees',
        parent=fees,
        defaults={'category_type': 'Education'},
    )
    Category.objects.get_or_create(
        name='Tuition Fees',
        parent=school_fees,
        defaults={'category_type': 'Education'},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='category',
                    name='parent',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subcategories',
                        to='core.category',
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='category',
                    name='category_type',
                    field=models.CharField(max_length=100),
                ),
            ],
        ),
        migrations.RunPython(normalize_expense_descriptions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(assign_budget_owners, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_sample_category_tree, migrations.RunPython.noop),
    ]
