# Generated by Django 6.0.2 on 2026-03-10 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_hierarchy_and_budget_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='category',
                    name='parent',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(
                choices=[
                    ('FOOD', 'Food'),
                    ('TRAVEL', 'Travel'),
                    ('UTILITIES', 'Utilities'),
                    ('EDUCATION', 'Education'),
                    ('ENTERTAINMENT', 'Entertainment'),
                    ('HEALTH', 'Health'),
                    ('SHOPPING', 'Shopping'),
                    ('OTHER', 'Other'),
                ],
                max_length=50,
            ),
        ),
    ]
