from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

urlpatterns = [
    path('', views.landing, name='landing_page'),
    path('landing/', views.landing, name='landing'),
    path('register/', views.register, name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/', views.simple_password_reset, name='password_reset'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('admin-analytics/', views.admin_analytics, name='admin_analytics'),
    path('admin/system-reports/', views.admin_system_reports, name='admin_system_reports'),
    path('admin-analytics/export/pdf/', views.export_admin_analytics_pdf, name='export_admin_analytics_pdf'),
    path('admin-analytics/export/csv/', views.export_admin_analytics_csv, name='export_admin_analytics_csv'),
    path('admin/financials/<str:metric_type>/', views.admin_financial_breakdown, name='admin_financial_breakdown'),
    path('admin/users/', views.admin_users, name='admin_users'),
    path('admin/users/delete/<int:id>/', views.delete_user, name='delete_user'),
    path('admin/users/toggle/<int:id>/', views.toggle_user_status, name='toggle_user'),
    path('admin/accounts/', views.admin_accounts, name='admin_accounts'),
    path('admin/categories/', views.admin_categories, name='admin_categories'),
    path('admin/categories/<int:id>/edit/', views.edit_category, name='edit_category'),
    path('admin/category-types/', views.admin_category_types, name='admin_category_types'),
    path('admin/category-types/<int:id>/edit/', views.edit_category_type, name='edit_category_type'),
    path('admin/category-types/<int:id>/delete/', views.delete_category_type, name='delete_category_type'),
    path('admin/activity-log/', views.admin_activity_log, name='admin_activity_log'),
    path('notifications/', views.notifications, name='notifications'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('dashboard/snapshot/', views.account_snapshot, name='account_snapshot'),
    path('financial-overview/', views.financial_overview, name='financial_overview'),
    path('ai-chatbot/', views.ai_chatbot, name='ai_chatbot'),
    path('ai-chatbot/reply/', views.ai_chatbot_reply, name='ai_chatbot_reply'),
    path('export/pdf/', views.export_group_pdf, name='export_group_pdf'),
    path('download-report/<str:format>/', views.download_report, name='download_report'),
    path('analysis/', views.financial_analysis, name='financial_analysis'),
    path('expenses/', views.expense_history, name='expense_history'),
    path('expenses/<int:id>/edit/', views.edit_expense, name='edit_expense'),
    path('expenses/<int:id>/delete/', views.delete_expense, name='delete_expense'),
    path('budgets/', views.budget_history, name='budget_history'),
    path('budgets/<int:id>/edit/', views.edit_budget, name='edit_budget'),
    path('budgets/<int:id>/delete/', views.delete_budget, name='delete_budget'),
    path('incomes/', views.income_history, name='income_history'),
    path('incomes/<int:id>/edit/', views.edit_income, name='edit_income'),
    path('incomes/<int:id>/delete/', views.delete_income, name='delete_income'),
    path('categories/delete/<int:id>/', views.delete_category, name='delete_category'),
    path('add-expense/', views.add_expense, name='add_expense'),
    path('add-budget/', views.add_budget, name='add_budget'),
    path('add-income/', views.add_income, name='add_income'),
]
